### ISSUE TITLE
Hard to differentiate between suggested search results

### ISSUE THREAD

**Issue by mcapodici** [headwaymaps/headway#110]
**Steps to reproduce**

* Visit 
* Enter "pitt street, sydney" into the Where To? Box

**Expected Result**

Each result is unique

**Actual Result**

There are 3 different results with exactly the same text and subtext.

![image](https://user-images.githubusercontent.com/3528831/186041098-01d36d91-6788-45b4-9212-ba2fcb7dc5a6.png)

**Comment by mcapodici** [comment]
I am a web dev, and I am happy to try to fix and make a PR. However I would like to know if it is worth it (are you taking external contributions, and reviewing them, etc.).

**Comment by ellenhp** [comment]
It looks like each of the results has a different localadmin value

https://maps.earth/pelias/v1/autocomplete?text=pitt%20street%2C%20sydney

From OSM's perspective they're all different ways, presumably because they get split at the local admin boundary? I ran a request to geocode.earth for the same thing (output attached) and I do notice a similar effect where one street for each localadmin is returned.

[output.txt](https://github.com/headwaymaps/headway/files/9398441/output.txt)

> I am a web dev, and I am happy to try to fix and make a PR. However I would like to know if it is worth it (are you taking external contributions, and reviewing them, etc.).

Yes! I am very much taking contributions. :) A lot of the maps.earth geocoding quality issues seem to be related to configuration of pelias but this one might just be something we have to work around client-side. I'm not sure how/if these should be deduplicated though. Maybe it makes sense to add the localadmin to the gray subtitle for each list item? Other ideas?

**Comment by ellenhp** [comment]
By the way, for frontend development there's no need to run an instance of the stack yourself, so you don't have to install earthly or anything. All the requests for data are proxied from the quasar dev server to maps.earth, so you can make changes locally and have the whole app hot-reload without having to bring the server up and down. It's been pretty painless for me so far, but let me know if you run into issues.

**Comment by mcapodici** [comment]
I think trying to do something clever (like work out the "correct one") in the front end would be a mistake, since there will all sorts of edge cases for different towns and streets. The raw data makes sense, and it has found various things, like a church and a shopping mall. I don't think the data looks too bad there.

Displaying some additional information and letting the user decide sounds good. You suggested the `localadmin`, that looks good. There is also `label`, which might be good. It feels like something to experiment with with many different locations.

**Comment by ellenhp** [comment]
If you dig very deep into the frontend you'll realize pretty quickly that it's full of hacks, so I encourage you to take creative liberty if you dive into this and change whatever you need to change.

I don't think I want to use `label` because it duplicates data that we already display (the `name`). I propose we construct a label for the gray subtitle thing based on joining the following values with a comma, omitting anything that is null or empty: `neighbourhood`, `locality`, `region`, `country`

There might be a case for adding `county` but at least where I'm from that wouldn't be very helpful unless `neighbourhood` and `locality` were both missing.

Does this sound right to you?

**Comment by mcapodici** [comment]
Sounds good to me! 👍

**Comment by ellenhp** [comment]
The optimistically-named `localizeAddress` is I think where you want to look, but you might need to change the fields defined in the POIs themselves, as well as the logic that parses them from the pelias response.

**Comment by ellenhp** [comment]
I should also mention that this is probably the correct thing to do only for streets. I think existing localization methods work well for POIs tagged with address information, so doing this only for `layer == "street"` makes sense to me.

**Comment by ellenhp** [comment]
@mcapodici  I just found this project which would enable `localizeAddress` to *actually* localize addresses. https://github.com/OpenCageData/address-formatting

Looks extremely promising, if slightly unrelated to what you're fixing

**Comment by mcapodici** [comment]
> By the way, for frontend development there's no need to run an instance of the stack yourself, so you don't have to install earthly or anything. All the requests for data are proxied from the quasar dev server to maps.earth, so you can make changes locally and have the whole app hot-reload without having to bring the server up and down. It's been pretty painless for me so far, but let me know if you run into issues.

Here are some problems I am getting:

```
docker-compose up -d
WARNING: The HEADWAY_FORCE_BBOX variable is not set. Defaulting to a blank string.
Starting headway_pelias_elastic_init_1 ... 
Starting headway_peliasplaceholder_init_1 ... 
Starting headway_pelias_elastic_init_1    ... done
Starting headway_nginx_init_1             ... done
Starting headway_pelias_config_init_1     ... done
Starting headway_mbtileserver_init_1      ... done
Starting headway_valhalla_init_1          ... done
Starting headway_otp_init_1               ... done
headway_otp_1 is up-to-date
Creating headway_mbtileserver_1           ... done

ERROR: for peliasplaceholder  Container "01919c327efe" exited with code 2.

ERROR: for valhalla  Container "9c1d1a07036a" exited with code 1.

ERROR: for peliaselasticsearch  Container "813888d0a74e" exited with code 2.
ERROR: Encountered errors while bringing up the project.
```

Using Docker Desktop on Windows (I would prefer Linux but having other issues with the Linux install at the moment).

Nothing is served on http://localhost:8080/, I don't think the nginx container is running.

I didn't use earthly (I did try to install anyway to see if it could fix this, but had trouble installing it), however hopefully it is possible to get it working without installing that.

# Other details

## .env:

```
HEADWAY_AREA=Sydney
HEADWAY_PUBLIC_URL=http://127.0.0.1:8080
HEADWAY_HTTP_PORT=8080
```

**Comment by ellenhp** [comment]
You do need to run Earthly to generate the data required to run the stack, however if you were okay with testing using Adelaide instead of Sydney I do have some pre-generated artifacts you can download:

https://publicdata.ellenhp.workers.dev/Adelaide.elasticsearch.tar
https://publicdata.ellenhp.workers.dev/Adelaide.graph.obj
https://publicdata.ellenhp.workers.dev/Adelaide.mbtiles
https://publicdata.ellenhp.workers.dev/Adelaide.pelias.json
https://publicdata.ellenhp.workers.dev/Adelaide.placeholder.tar
https://publicdata.ellenhp.workers.dev/Adelaide.valhalla.tar
https://publicdata.ellenhp.workers.dev/fonts.tar
https://publicdata.ellenhp.workers.dev/sprite.tar

If you download all of these and put them inside the data directory of the headway repo you should be able to change the `.env` file to use Adelaide instead of syndney, then `docker-compose down --volumes` then `docker-compose up -d` and I think things will come up. But in general you do need earthly.

**Comment by ellenhp** [comment]
Also maybe I didn't communicate this well, but you don't need to run the stack at all for frontend dev on Headway, so no earthly, no docker, etc. Just Quasar CLI tools. Run `quasar dev` in the web/frontend directory and everything should come up, and all the requests for tiles, searches, route requests etc will be proxied to my demo server by quasar, rewriting headers as needed to get around CORS stuff.

It turns out though that the OpenCageData localization dataset I linked has a really nice JS library and it does seem to handle streets well though so I think I fixed this by including that. Huge localization win IMO. I also learned that apparently out in Australia you don't put a comma between city and state? That's the kind of thing that I never would have thought to check so I'm glad I found this library.

Will have a PR up to fix this soon, but I'm going to try to go back to sleep first. I hate insomnia :upside_down_face:

**Comment by mcapodici** [comment]
Thanks for the information. I was trying to get the stack working. I managed to get a lot further with that - getting earthly to build and get the containers running and some of the site working (but still with errors). It is quite interesting and a lot of tech there I had never seen before. I will try with the `quasar` tool.

I had a look at your fix - looks good. Handy there is an npm package for this kind of problem and you have probably solved this problem more generally like that.

I will keep an eye out for other front end things to fix. Feel free to point me at something.

**Comment by ellenhp** [comment]
Cool! If you wanted to try and get the frontend set up for translations that would be amazing. I wanna try and support a few languages for the first versioned release.  There were also some hacks I've had to do to reference the basemap component in other parts of the page that I'd love to remove somehow so if you wanted to look at that it would be very welcome too. :) Thank you by the way!
